AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Community Board Handler

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: CBHandler
      Handler: lambda.lambda_handler  # Update with the correct module and function name
      Runtime: python3.8  # Use the appropriate Python runtime
      CodeUri: .  # Path to your Lambda deployment package
      Timeout: 10  # Maximum execution time in seconds
      MemorySize: 128  # Maximum memory allocation in MB
      Environment:
        Variables:
          KEY1: VALUE1  # Environment variables for your Lambda
      Role: YourLambdaExecutionRole  # ARN or name of the Lambda execution role
